
language: java
jdk:
  - openjdk14

sudo: false

script: mvn clean package -DskipTests=true

services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      a.s.kirson@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    CODECOV_TOKEN="73d6a97d-8e18-408e-acdd-432065246095"

deploy:
  api_key:
    secure: t52oJVMWxgbbG+SxqnTlcEWfFmgQcG1T6U8D75ahQyLrk2v3BZDzacJlt343L0qcS0oKlFGK7bK1iLFBWv1kGblJIWRa6PddymFMZJt+UBa6PrNO6/HsFqmZl2PpdRnwgx0p6Nj3/O8plUyi5FJwC7piDjjXmyiXh23fWTMEVsymUDTpycpoan5r46GUMjQT2gc2mErHYyMO75i+lPl6JPwDGWRdKUPfi2ChHXvjqQfsE9U6iSpnWbN5cuOPT4qIG+hpRN1VT8qgEznUfg6Yb6kiKBqn30KQ2G6O8eSCcK4nZw3yZIc6kv9tKR8t26Ez9XiPJ8mfMojJJ2nwEeA9A4xC/rnaf4UhJuLV4plDd7+OvkztOhIaYEGZbLqoMTKIhTNRZmPBEQcEaNr9AzgPSkhhtW5ny8zxZV4sxnCF4PHdTfMAoII8/YVY8P9l0MnQbSeCi9Akt8LbZ4xyt5rjbLUvkZtq8SSSqZm5Qx6wyaYjNQ/QM4L5tHcdCtACoGoLdQ3P2kBsLwTRvpQ5fpOC9y3rsc3V38QlHBfJJzjoPJm3HrvUFn/Ebww00KEX4+zsqt9ip/WmOozLL4hbJmI7vqSC0STkT9I0TyguyIl/nN3mK5HuVB99znQYuZbvlPPnsGBFUx1xuO1GAfip+xirfh9UfLyGK/s74s02kcswnT0=
app: immense-reef-07818