language: java
jdk:
- openjdk14
sudo: false
script: mvn clean package -DskipTests=true
services:
- postgresql
before_install:
- psql -c 'create database forum;' -U postgres
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients: a.s.kirson@gmail.com
    on_success: never
    on_failure: always
env:
  global:
  - CODECOV_TOKEN=:"73d6a97d-8e18-408e-acdd-432065246095"
deploy:
  provider: heroku
  api_key:
    secure: ZLFYmmgGYI4/7Cu4JqUFkwacsqzKweGlNXehnc2pf7QhVspIQbg8ZoT165d0P6VzDbQeDtB16jt227HMoPZKpNfUJ0R6TgIZ9OwBiW13ngLkGehs3oYhDo371JW5FgcMrkffXuY1E87r4UKBQ84UKliZiLp0UjrxbW35ERqvDh3fLK/Rye6n4aouRYFP4Yc0ACSPuPJFrA2u7GdnjAtvwBtt7lcaF6GGkNQNNqotboAt0S9n9yl8pqgzn5BAGs0YdwLWdn4bqhrEsDcH7sXv7HL8GTxWsNouR8KwuqdHJrbjWOK8GcNAyBiKeKZnxAJOOqNmvPoRGOuARImSiv/Z7oujAYTXYyim+3dVLt9H79btDX3oV+hDCHxN83IAwjNHaq2w+iE25Jl5S9MIt4FUDJgRX5614zuqMs75rL8XXnMlL/cHWnANvnJ0O2Hbr1rZALGUz3/WHJcyyF0hp+9TdSLvV0IJdZiN3MSIUXxZXccTAv3WuGsIovjyWw3gdU3JfjOyMsx5E05e4zVbTIuynAKn7n/rzZfvJFC80I/178Zv8n32pCPyyS/acrvLroggh/rPME0p/rvDKWMuakMDQmoWZWHNbm6Yxx9+wjDZJW1q/W5ZxXDuZsNW3SUthoUywZKmqH8P7N765M2wdG5kU8uXMt3qxIvPyAoIpPfm1uw=
  app: forum-1