# используем режим обычного пользователя для сборки проекта.
sudo: false

language: java
jdk:
- openjdk14

script: mvn clean package -DskipTests=true

services:
- postgresql

before_install:
- psql -c 'create database forum;' -U postgres

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients: a.s.kirson@gmail.com
    on_success: never
    on_failure: always

env:
  global:
  - CODECOV_TOKEN=:"73d6a97d-8e18-408e-acdd-432065246095"

deploy:
  provider: heroku
  api_key:
    secure: P0MUdRySrpoGDFIb98B/flOLo1/G8wulxI9fuKTRj7KrzctOIJxzmc19u9XqIZaKf0j0cCDV853NY2y0hmO3aKB6DQpmE2y1rpl5QD/HYIkMp3WKAuEtE/KPJBzV0yMXvqy/9mZKD0tcAbQRWpYYpbh3x8RqILLku96wVT6lahLQye+i03BU+K2C4WJcVlBYIic3CoyqcHEe3icHHf+X0a544DdZVO9cM8x/rxr7cRhqP4eXwI9aM/gCIBwyCw7nUTwvy2ZUVv7vq3zG4Wd1uZvzdKshYc3dXdYFNPyU9b8kjxQadjX7oRDOO6ZWCmAsTxZygwKcUdQZx5odq4uuUOjHpZKgeJTMx/KqTJeMukRgxxF9T4OM0CK10ilywf9rXLN4YhqiLTI0KisE9ghUm5IZ4Im71yQXwd4vi34sYS4jug37JnnW96anu1vOEbCPkz8f0snk7IOgNhGkWuU5iYol/WjcichB+6ZO0k3fm/DXG07Nck20UUshzJIYvB/M/laHpWHV6/EbHbZCuimmqyxop2TXteACiT3jO6c99p2v2GBPOxRukLMIbi5f9U+plP4W6KXxsjRfYbZfiPbX4BfY25UStuMHc5DLxfkjZDgdD71IbFzjYTooqNDWxPY164Fq2eeGyNJ4Q6WrxnLVsKc1mFrvNiRZDfmdvL5ROrA=
  app: forum-1