language: java
jdk:
- openjdk14
sudo: false
script: mvn clean package -DskipTests=true
services:
- postgresql
before_install:
- psql -c 'create database forum;' -U postgres
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients: a.s.kirson@gmail.com
    on_success: never
    on_failure: always
env:
  global:
  - CODECOV_TOKEN=:"73d6a97d-8e18-408e-acdd-432065246095"
deploy:
  provider: heroku
  api_key:
    secure: "TzEKrZFlx3WJejbXKHiLAzEwidYErttI+XVYrdTDtnftmWP9uOv1MXaU1MNorTXfXpKJEhvwl4B0BuEVYxOygUDT0Skx+m+cyNGS+d9llZ8UlOn7PS2kJUQrGPdf8S5ll0IgE+fBclt+pbw8nFyCa76719DCR62ikOvM+ehp2Pvrz/DMoGAJABCQrZkQicKfMJdT8PjqJ86jDJZZf567Z4APmgVcbHxYQly9hO9fQkMNBuoFwRqa2dG7qltK12b+FNohRYj3Pg4AdAVYv1Ng5bDd7XP7HnitlCKOvstkC6WKN/0dpf2/xHiGN76YhG/W/+JLUS/B677Q7k6MXVxPLZyLNzYAdK9xSrRydH/rTvNVC0x5amXqBgHIstPq/cMC5WEs2BTYFlqWb0kcs9UIeSB71U0fwz/tjnQIxa0K8tircVDPNpPPS5KzvHTmiwuuM9YXPwga9ju2ZvcNg+RKsatZG3mwiAikhpAckhwIK8dWpLeajkngUISzuoH/FWQFSNNrqTyuD58qrp5fH4hnArYfmjGPVDtD77nPo6jw9U+4othdm3LeBqtVHhKTRrBTEIo9r6wMR75eoaWYFAXfhNUsvBujyGtyDjlwlX0B249Fx4YlhTz3l4uY2QSCJ9D4jxsAK8S3NzI1ymMIW3u0neXChABHleu6oRq3y0/aVKk="
      app: forum-1